config/routes.rb
Rails.application.routes.draw do
  get "orders/create"
  get "orders/index"
  get "orders/show"
  devise_for :users
  get "/home", to: "home#index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"
  get "/shop", to: "categories#index"
  get "/shop/:id", to: "categories#show"
  get "product/:id", to: "products#index"
  get "/search", to: "categories#search"
  get "/order", to: "orders#index"
  get "/about", to: "about#index"
  get "/contact", to: "contact#index"

  post "order", to: "orders#create", as: "create_order"

  resources :cart, only: %i[create destroy]
  resources :order, only: %i[create destroy]
end

app/models/about.rb
class About < ApplicationRecord

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  validates :name, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category

  validates :name, :price, :qty, presence: true

  paginates_per 4
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @about = About.find(1)
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def create
    logger.debug("Adding #{params[:id]} to cart.")
    id = params[:id].to_i
    unless session[:shopping_cart].include?(id)
      session[:shopping_cart] << id
      product = Product.find(id)
      flash[:notice] = "+ #{product.name} added to cart"
    end
    # session[:shopping_cart] << id
    redirect_to "/shop"
  end

  def destroy
    id = params[:id].to_i
    session[:shopping_cart].delete(id)
    product = Product.find(id)
    flash[:notice] = "- #{product.name} removed from cart."

    redirect_to "/shop"
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
    @contact = Contact.find(1)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    tax = 1.0

    tax = 1.05 if params[:province] == "AB"
    tax = 1.12 if params[:province] == "BC"
    tax = 1.12 if params[:province] == "MB"
    tax = 1.15 if params[:province] == "NB"
    tax = 1.15 if params[:province] == "NL"
    tax = 1.05 if params[:province] == "NT"
    tax = 1.15 if params[:province] == "NS"
    tax = 1.05 if params[:province] == "NU"
    tax = 1.13 if params[:province] == "ON"
    tax = 1.15 if params[:province] == "PE"
    tax = 1.14975 if params[:province] == "QC"
    tax = 1.11 if params[:province] == "SK"
    tax = 1.05 if params[:province] == "YT"

    total = (params[:total].to_f * tax).round(2).to_s
    logger.debug("BUYING #{params[:total].to_f * tax} BUYING.")
    @order = Order.new
    @order.name = params[:name]
    @order.province = params[:province]
    @order.total = total
    @order.save
    session[:shopping_cart].clear

    @customer = Customer.new
    @customer.name = params[:name]
    @customer.province = params[:province]
    @customer.order_id = @order.id
    @customer.save
    flash[:notice] = "Order #{@order.id} Completed. Confirmation email in 2-3 days. Total with taxes: #{total}"
    redirect_to "/shop"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  # Only allow a list of trusted parameters through.
  def order_params
    params.require(:order).permit(:name, :province, :total)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @category = Category.find(params[:id])
    @products = Product.where(category_id: params[:id])
    @categories = Category.all
  end

  def show; end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/about/index.html.erb
<div class="container-fluid d-column-row justify-content-center ">
<h1><%= @about.title%></h1>
  <div class="row">
    <div class="col-lg-4">
      <p><%= @about.about_us%></p>
    </div>
  </div>
  <div class ="row">
  <div class="col-sm-4">
  <div>
    <img class="img-fluid" src="<%= @about.image%>" alt="AboutImage">
    </div>
  </div>
  </div>
</div>

app/views/contact/index.html.erb
<div class="container-fluid d-column-row justify-content-center ">
<h1>Contact Us</h1>
  <div class="row">
    <div class="col-lg-4 ">
      <p>If you have any questions or concerns send us an email and we will reply with 2-3 business days.</p>
    </div>
  </div>
  <div class ="row">
  <div class="col-sm-4">
  <p><a href="mailto: <%= @contact.email_address%>"><%= @contact.email_address%></a></p>
  </div>
</div>

app/views/orders/_form.html.erb
<%= form_for(order_url) do |f|%>
  Full Name: <%= f.text_field :name %>
  Province: <%= f.text_field :province %>
  Total: <%= f.hidden_field :total %>
  <%= f.submit %>
<% end %>

app/views/orders/_item.html.erb
<ul style="list-style-type: none;">
      <li>

        <% if cart.present? %>
          <% total = 0%>
          <sup><%= cart.size %></sup>
          <ul style="list-style-type: none;">
            <% cart.each do |p| %>
              <li>
                <%= p.name%> || <%= p.price%> || <%= button_to cart_path(p.id), method: :delete, class: "btn btn-primary mt-2" do%> Remove from cart - <% end %>
                ------------------
                <% total = total + p.price%>
              </li>
            <% end %>
          <li>Total is <%= total %> + taxes</li>
          </ul>

          <% else %>
          <p>Cart is empty.</p>

        <% end %>
    </ul>
<h2>Information</h2>

<%= form_with url: create_order_path, local: true, method:  :post do |f| %>
    Full Name: <%= f.text_field :name %>
    Province: <%= f.select(:province, ['AB', 'BC', 'MB', 'NB', 'NL', 'NT', 'NS', 'NU', 'ON', 'PE', 'QC', 'SK', 'YT' ]) %>
    <%= hidden_field_tag(:total, total) %>
    <p>Taxes calculated after purchase</p>
    Total: <%= total %>
    <%= f.submit 'BUY' %>
<% end %>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/index.html.erb
<div class="container">
<h2>Order Summary</h2>
<%= render "orders/item" %>


</div>

app/views/orders/show.html.erb
<h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p>

app/views/products/index.html.erb
<link rel="stylesheet" href="/Users/colemancapsule/Documents/RRCWEBD3008/collectors_club_v3/app/assets/stylesheets/shop.css">
<div class='container'>

<%= render "/categories/searchbar"%>

<div class='container'>
<h2 style="text-align: center">Categories</h2>
<div class="container text-center">
  <div class="row">
  <% @categories.each do |category| %>
    <div class="col">
    <a class="btn btn-outline-primary mb-3 mt-3" href="/product/<%= category.id %>"><%= category.name %></a>
    </div>


  <% end %>
  <div class="col">
    <a class="btn btn-outline-primary mb-3 mt-3" href="/shop">Shop All</a>
  </div>
</div>
</div>

<p>Current Category: <%= @category.name%></p>

<%= render "/categories/product"%>
</div>
</div>