config/routes.rb
Rails.application.routes.draw do
  get "orders/create"
  get "orders/index"
  get "orders/show"
  devise_for :users
  get "/home", to: "home#index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"
  get "/shop", to: "categories#index"
  get "/shop/:id", to: "categories#show"
  get "product/:id", to: "products#index"
  get "/search", to: "categories#search"
  get "/order", to: "orders#index"
  get "/about", to: "about#index"
  get "/contact", to: "contact#index"

  post "order", to: "orders#create", as: "create_order"

  resources :cart, only: %i[create destroy]
  resources :order, only: %i[create destroy]
end

app/models/about.rb
class About < ApplicationRecord

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  validates :name, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category

  validates :name, :price, :qty, presence: true

  paginates_per 4
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @about = About.find(1)
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def create
    logger.debug("Adding #{params[:id]} to cart.")
    id = params[:id].to_i
    unless session[:shopping_cart].include?(id)
      session[:shopping_cart] << id
      product = Product.find(id)
      flash[:notice] = "+ #{product.name} added to cart"
    end
    # session[:shopping_cart] << id
    redirect_to "/shop"
  end

  def destroy
    id = params[:id].to_i
    session[:shopping_cart].delete(id)
    product = Product.find(id)
    flash[:notice] = "- #{product.name} removed from cart."

    redirect_to "/shop"
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
    @products = Product.all.page(params[:page])
    # session[:visit_count] ||= 0
    # session[:visit_count] += 1
    # @visit_count = session[:visit_count]
  end

  def show
    @product = Product.where(id: params[:id])
  end

  def search
    # wildcard_search = "%#{params[:keywords]}%"
    if params[:ccs].empty?
      # @products = Product.where(category_id: params[:ccs]).where("name LIKE ? OR description LIKE ?", "%" + params[:q] + "%", "%" + params[:q] + "%")
      @products = Product.where("name LIKE ?", "%" + params[:q] + "%")
    else
      # @products = Product.where("name LIKE ?", "%" + params[:q] + "%")
      @products = Product.where(category_id: params[:ccs]).where(
        "name LIKE ? OR description LIKE ?", "%" + params[:q] + "%", "%" + params[:q] + "%"
      )
    end
    # @products = Product.where("name LIKE ?", "%" + params[:q] + "%")
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  # Only allow a list of trusted parameters through.
  def product_params
    params.require(:product).permit(:name, :description, :qty, :search)
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
    @contact = Contact.find(1)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    tax = 1.0

    tax = 1.05 if params[:province] == "AB"
    tax = 1.12 if params[:province] == "BC"
    tax = 1.12 if params[:province] == "MB"
    tax = 1.15 if params[:province] == "NB"
    tax = 1.15 if params[:province] == "NL"
    tax = 1.05 if params[:province] == "NT"
    tax = 1.15 if params[:province] == "NS"
    tax = 1.05 if params[:province] == "NU"
    tax = 1.13 if params[:province] == "ON"
    tax = 1.15 if params[:province] == "PE"
    tax = 1.14975 if params[:province] == "QC"
    tax = 1.11 if params[:province] == "SK"
    tax = 1.05 if params[:province] == "YT"

    total = (params[:total].to_f * tax).round(2).to_s
    logger.debug("BUYING #{params[:total].to_f * tax} BUYING.")
    @order = Order.new
    @order.name = params[:name]
    @order.province = params[:province]
    @order.total = total
    @order.save
    session[:shopping_cart].clear

    @customer = Customer.new
    @customer.name = params[:name]
    @customer.province = params[:province]
    @customer.order_id = @order.id
    @customer.save
    flash[:notice] = "Order #{@order.id} Completed. Confirmation email in 2-3 days. Total with taxes: #{total}"
    redirect_to "/shop"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  # Only allow a list of trusted parameters through.
  def order_params
    params.require(:order).permit(:name, :province, :total)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_product.html.erb
  <div class="container">
    <div class="d-flex flex-wrap justify-content-between">
      <% @products.each do |product| %>

        <div class="card mb-5" style="width: 18rem;">
          <img class="card-img-top" src="<%= product.image%>" alt="Card image cap">
          <div class="card-body">
            <h5 class="card-title"><%= product.name%></h5>
            <p class="card-text"><%= product.description%></p>
            <p class="card-text">$<%= product.price%></p>
            <a href="/shop/<%= product.id%>" class="btn btn-primary">View</a>




            <% if cart.include?(product) %>
              <%= button_to cart_path(product) , method: :delete, class: "btn btn-primary mt-2" do%>
              - Remove from cart
              <% end %>
          <% else %>
              <%= form_with url: cart_index_path, method: :post do%>
                <%= hidden_field_tag(:id, product.id) %>
                <%= button_tag '+ Add to Cart', class: "btn btn-primary mt-2"%>
              <% end %>
            <% end%>
          </div>
        </div>

      <% end %>

    </div>
  </div>

app/views/categories/_searchbar.html.erb
<div class="container">
<h3>Search By Keyword: </h3>
<form action="/search" class="form-row">
  <div class="col">
  <input name="q" type="text" placeholder="Search">


  <label for="ccs">Choose a category:</label>
  <select id="ccs" name="ccs">
    <option value="">All</option>
    <option value="1">Sealed Prouct</option>
    <option value="2">Graded Cards</option>
    <option value="3">Singles</option>
  </select>


  <button class="btn btn-secondary" type="submit">Search</button>
  </div>
</form>
</div>

app/views/categories/index.html.erb
<link rel="stylesheet" href="/Users/colemancapsule/Documents/RRCWEBD3008/collectors_club_v3/app/assets/stylesheets/shop.css">

<%= render "searchbar" %>



<h2 style="text-align: center">Categories</h2>
<div class="container text-center">
  <div class="row">
  <% @categories.each do |category| %>
    <div class="col">
    <a class="btn btn-outline-primary mb-5 mt-3" href="/product/<%= category.id %>"><%= category.name %></a>
    </div>


  <% end %>
  <div class="col">
    <a href="/shop" class="btn btn-outline-primary mb-5 mt-3" >Shop All</a>
  </div>
</div>
</div>



<%= render "product"%>



  <div class='container d-flex justify-content-center'>
  <div class='mb-5'>
  <%= paginate @products%>
  </div>


  </div>

app/views/categories/search.html.erb
<div class='container'>
<%= render "searchbar"%>
<p>
  Found <%= pluralize(@products.count, 'Product') %> when searching for: <%= params[:q] %>
</p>
<%= render "product"%>
</div>
</div>

app/views/categories/show.html.erb
<div class="container">
<% @product.each do |item| %>

<div class="d-flex-column justify-content-center">
<div class="m-r-5">
  <div>
    <img class="img-fluid" src="<%= item.image%>" alt="Card image cap" >
  </div>
</div>

<div class="m-5">
  <h3><%= item.name%></h3>
  <p><%= item.description%></p>
  <p>$<%= item.price %></p>
  <p>QTY: <%= item.qty %></p>

    <% if cart.include?(item) %>
      <%= button_to cart_path(item) , method: :delete, class: "btn btn-primary mt-2" do%>
      - Remove from cart
      <% end %>
    <% else %>
      <%= form_with url: cart_index_path, method: :post do%>
        <%= hidden_field_tag(:id, item.id) %>
        <%= button_tag '+ Add to Cart', class: "btn btn-primary mt-2"%>
      <% end %>
    <% end%>
  </div>
</div>




<%end%>
</div>